### PR TITLE
Trim access key id/secret

### PR DESCRIPTION
**Pull request by rockuw**

### CODE REVIEW

**Comment by zensh** [comment]
I don't think it's necessary. Developer should provide explicitly options.

**Comment by rockuw** [comment]
@zensh It has its value in reducing the OSS tickets about 'SignatureDoesNotMatch'/'AccessDenied'.

**Comment by dead-horse** [comment]
@zensh 现在有许多用户出现了这个问题，先合并吧，@rockuw 4.1.7

**Comment by rockuw** [comment]
@zensh 我们这边在做的一个事情是减少OSS的工单数，针对所有SDK，我们统计的签名错误工单数是372，trim导致的大概占一半。所以我们认为有必要在SDK中做trim。

**Pull request merged**
